<?php

/**
 * @file
 * Mail Login: This module enables users to login by email address.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function mail_login_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login_form':
      // Load module configurations.
      $config_factory = \Drupal::configFactory();
      $config = $config_factory->get('mail_login.settings');
      // Check for settings to enable login by email address.
      if ($config->get('mail_login_enabled') &&
        $config->get('mail_login_override_login_labels')) {
        // Check for settings to override login form username
        // title and description.
        $form['name']['#title'] = t($config->get('mail_login_username_title'));
        $form['name']['#description'] = t($config->get('mail_login_username_description'));
      }
      break;
  }
}
