mail_login.settings:
  type: config_object
  label: 'Mail Login settings'
  mapping:
    mail_login_enabled:
      type: integer
      label: 'Mail Login enabled'
    mail_login_override_login_labels:
      type: integer
      label: 'Override login labels'
    mail_login_username_title:
      type: string
      label: 'Username title'
    mail_login_username_description:
      type: string
      label: 'Username description'
